name: Backend CI - Test, Build and Push to ACR

on:
  push:
    branches:
      - testing

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python for running backend tests
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install deps and run tests for each backend service
      - name: Run backend tests
        run: |
          cd backend/customer_service && pip install -r requirements-dev.txt && pytest || exit 1
          cd ../product_service && pip install -r requirements-dev.txt && pytest || exit 1
          cd ../order_service && pip install -r requirements-dev.txt && pytest || exit 1

      # Azure login (using service principal JSON in secret)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and push Docker images
      - name: Build and push images
        run: |
          az acr login --name $ACR_LOGIN_SERVER

          docker build -t $ACR_LOGIN_SERVER/customer_service:${IMAGE_TAG} ./backend/customer_service
          docker push $ACR_LOGIN_SERVER/customer_service:${IMAGE_TAG}

          docker build -t $ACR_LOGIN_SERVER/product_service:${IMAGE_TAG} ./backend/product_service
          docker push $ACR_LOGIN_SERVER/product_service:${IMAGE_TAG}

          docker build -t $ACR_LOGIN_SERVER/order_service:${IMAGE_TAG} ./backend/order_service
          docker push $ACR_LOGIN_SERVER/order_service:${IMAGE_TAG}

          docker build -t $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG} ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:${IMAGE_TAG}
